> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# numpy functions


### 5 useful functions

Write a short introduction about Numpy and list the chosen functions. 

- format_float_positional (x[, precision, …]) Format a floating-point scalar as a decimal string in positional notation.
- format_float_scientific (x[, precision, …]) Format a floating-point scalar as a decimal string in scientific notation.
- array_repr (arr[, max_line_width, precision, …]) Return the string representation of an array.
- array2string (a[, max_line_width, precision, …]) Return a string representation of an array.
- array_str (a[, max_line_width, precision, …]) Return a string representation of the data in an array.



The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Creating a new project "amaanafif999/numpy-array-operations"
[jovian] Committed successfully! https://jovian.ai/amaanafif999/numpy-array-operations


'https://jovian.ai/amaanafif999/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.array2string
function2 = np.array_repr
function3 = np.array_str
function4 = np.format_float_positional 
function5 = np.format_float_scientific

## Function 1 - np.array2string

change the array and return string

In [7]:
# Create and simple array with complex numer
arr_1 = np.array([1e-16,1,2,3]) 

# Convert arrat to string using this function
result = np.array2string(arr_1,
                precision=2,
                separator=',',
                suppress_small=True)

Explanation about example

In [8]:
result

'[0.,1.,2.,3.]'

Explanation about example

In [9]:
type(result)

str

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [10]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amaanafif999/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/amaanafif999/numpy-array-operations


'https://jovian.ai/amaanafif999/numpy-array-operations'

## Function 2 - np.array_repr

In this function, we discuss about array_repr method, This method simply Return the string representation of an array.

numpy.array_repr(arr, max_line_width=None, precision=None, suppress_small=None)

In [17]:
# Example 1 - working
arr_1 = np.array_repr(np.array([1,2]))
print(arr_1)
arr_2 = np.array_repr(np.ma.array([0.]))
print(arr_2)
arr_3 = np.array_repr(np.array([], np.int32))
print(arr_3)
arr_4 = np.array_repr(np.array([], np.int64))
print(arr_4)

array([1, 2])
MaskedArray([0.])
array([], dtype=int32)
array([], dtype=int64)


In [18]:
# Example 2 - working
array_1 = np.array([1e-6, 4e-7, 2, 3])
print(array_1)
array_2 = np.array_repr(array_1, precision=6, suppress_small=True)
print(array_2)

[1.e-06 4.e-07 2.e+00 3.e+00]
array([0.000001, 0.      , 2.      , 3.      ])


In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amaanafif999/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/amaanafif999/numpy-array-operations


'https://jovian.ai/amaanafif999/numpy-array-operations'

## Function 3 - np.array_str

Return a string representation of the data in an array.

The data in the array is returned as a single string. This function is similar to array_repr, the difference being that array_repr also returns information on the kind of array and its data type

In [21]:
# Example 1 - working
array_1 = np.array_str(np.arange(3))
print(array_1)
array_2 = np.array_str(np.arange(3, 6))
print(array_2)
array_3 = np.array_str(np.arange(20, 500, 5))
print(array_3)

[0 1 2]
[3 4 5]
[ 20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95 100 105
 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185 190 195
 200 205 210 215 220 225 230 235 240 245 250 255 260 265 270 275 280 285
 290 295 300 305 310 315 320 325 330 335 340 345 350 355 360 365 370 375
 380 385 390 395 400 405 410 415 420 425 430 435 440 445 450 455 460 465
 470 475 480 485 490 495]


In [22]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amaanafif999/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/amaanafif999/numpy-array-operations


'https://jovian.ai/amaanafif999/numpy-array-operations'

##  Function 4 - np.format_float_positional

Format a floating-point scalar as a decimal string in positional notation

Provides control over rounding, trimming and padding. Uses and assumes IEEE unbiased rounding. Uses the “Dragon4” algorithm.

numpy.format_float_positional(x, precision=None, unique=True, fractional=True, trim='k', sign=False, pad_left=None, pad_right=None)


In [ ]:
# Example 1 - working
array_1 = np.format_float_positional(np.float64(np.pi))

In [23]:
array_1

'[0 1 2]'

In [24]:
# Example 2 - working
array_2 = np.format_float_positional(np.float32(np.pi))

In [25]:
array_2

'3.1415927'

In [26]:
# Example 3 - breaking (to illustrate when it breaks)
array_4 = np.format_float_positional(np.float8(np.pi))

AttributeError: module 'numpy' has no attribute 'float8'

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amaanafif999/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/amaanafif999/numpy-array-operations


'https://jovian.ai/amaanafif999/numpy-array-operations'

## Function  5 - np.format_float_scientific¶

Format a floating-point scalar as a decimal string in scientific notation.

Provides control over rounding, trimming and padding. Uses and assumes IEEE unbiased rounding. Uses the “Dragon4” algorithm.


In [28]:
# Example 1 - working
array_1 = np.format_float_scientific(np.float32(np.pi))

In [29]:
array_1

'3.1415927e+00'

In [30]:
# Example 2 - working
array_2 = np.format_float_scientific(np.float64(np.pi))

In [31]:
array_2

'3.141592653589793e+00'

Explanation about example

In [32]:
# Example 3 - breaking (to illustrate when it breaks)
array_6 = np.format_float_scientific(array_3, exp_digits=50)

TypeError: must be real number, not str

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

In [33]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amaanafif999/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/amaanafif999/numpy-array-operations


'https://jovian.ai/amaanafif999/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* numpy.array2string
* numpy.array_repr
* numpy.array_str
* numpy.format_float_positional
* numpy.format_float_scientific

In [35]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amaanafif999/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/amaanafif999/numpy-array-operations


'https://jovian.ai/amaanafif999/numpy-array-operations'